# Generated by Django 2.2 on 2022-08-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.URLField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(max_length=10000),
        ),
    ]
