# Generated by Django 3.2.9 on 2022-09-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='colour',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='logo',
            field=models.URLField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
