# Generated by Django 3.2.9 on 2022-10-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20221005_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='img',
        ),
        migrations.AddField(
            model_name='news',
            name='desc',
            field=models.TextField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
