# Generated by Django 3.2.9 on 2022-09-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220918_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='colour',
            new_name='color',
        ),
    ]
