# Generated by Django 3.2.9 on 2022-08-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(),
        ),
    ]
