# Generated by Django 3.2.9 on 2022-08-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220823_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
    ]
