# Generated by Django 3.2.9 on 2022-08-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.TextField(),
        ),
    ]
