# Generated by Django 3.2.9 on 2022-08-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(max_length=100000),
        ),
    ]
